ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/bps_hw
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/fw_inc
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include

obj-$(CONFIG_LEGACY_CAMERA) += bps_dev.o bps_core.o bps_soc.o
