ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sync
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_res_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_cci
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/

obj-$(CONFIG_LEGACY_CAMERA) += cam_ir_led_dev.o cam_ir_led_soc.o cam_ir_led_core.o
