ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cdm/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw

obj-$(CONFIG_LEGACY_CAMERA) += cam_vfe_top.o cam_vfe_top_ver2.o cam_vfe_camif_ver2.o cam_vfe_rdi.o
