ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_hyp_intf
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
obj-$(CONFIG_LEGACY_CAMERA) += cam_hyp_intf.o
