ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw

obj-$(CONFIG_LEGACY_CAMERA) += cam_vfe170.o cam_vfe_lite170.o
