ccflags-y += -I$(srctree)/techpack/camera-legacy/include/uapi
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils

obj-$(CONFIG_LEGACY_CAMERA) += 3dsl_eeprom_dev.o 3dsl_eeprom_core.o 3dsl_eeprom_soc.o
