ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_jpeg
ccflags-y += -Itechpack/camera_legacy/drivers/cam_jpeg/jpeg_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_jpeg/jpeg_hw/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_jpeg/jpeg_hw/jpeg_enc_hw

obj-$(CONFIG_LEGACY_CAMERA) += jpeg_enc_dev.o jpeg_enc_core.o jpeg_enc_soc.o
