ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sync
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cdm
ccflags-y += -Itechpack/camera_legacy/drivers/cam_lrme
ccflags-y += -Itechpack/camera_legacy/drivers/cam_lrme/lrme_hw_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -Itechpack/camera_legacy/drivers
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include/

obj-$(CONFIG_LEGACY_CAMERA) += lrme_hw_mgr/
obj-$(CONFIG_LEGACY_CAMERA) += cam_lrme_dev.o cam_lrme_context.o
