ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sync
ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils

obj-$(CONFIG_LEGACY_CAMERA) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
