ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_cci
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_res_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu
ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils

obj-$(CONFIG_LEGACY_CAMERA) += cam_flash_dev.o cam_flash_core.o cam_flash_soc.o
