ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/include


obj-$(CONFIG_LEGACY_CAMERA) += cam_vfe_soc.o cam_vfe_dev.o cam_vfe_core.o
obj-$(CONFIG_LEGACY_CAMERA) += vfe_bus/ vfe_top/ vfe170/