ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sync
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/fw_inc
ccflags-y += -Itechpack/camera_legacy/drivers
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/

obj-$(CONFIG_LEGACY_CAMERA) += icp_hw/
obj-$(CONFIG_LEGACY_CAMERA) += cam_icp_subdev.o cam_icp_context.o hfi.o
