ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_cci
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/

obj-$(CONFIG_LEGACY_CAMERA) += cam_sensor_io.o cam_sensor_cci_i2c.o cam_sensor_qup_i2c.o cam_sensor_spi.o
