ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cdm
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include

obj-$(CONFIG_LEGACY_CAMERA) += hw_utils/ isp_hw/
obj-$(CONFIG_LEGACY_CAMERA) += cam_isp_hw_mgr.o cam_ife_hw_mgr.o

