ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sensor_module/cam_cci
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core

obj-$(CONFIG_LEGACY_CAMERA) += cam_eeprom_dev.o cam_eeprom_core.o cam_eeprom_soc.o
