ccflags-y += -Itechpack/camera_legacy/drivers/isp/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/isp/isp_hw/hw_utils/include
ccflags-y += -Itechpack/camera_legacy/drivers/isp/isp_hw/isp_hw_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/icp_hw_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/fw_inc/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_sync
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/icp_hw_mgr/include/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_icp/icp_hw/a5_hw/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_cpas/include

obj-$(CONFIG_LEGACY_CAMERA) += cam_icp_hw_mgr.o
