ccflags-y += -Itechpack/camera_legacy/drivers/cam_utils
ccflags-y += -Itechpack/camera_legacy/drivers/cam_core
ccflags-y += -Itechpack/camera_legacy/drivers/cam_req_mgr
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Itechpack/camera_legacy/drivers/cam_isp/isp_hw_mgr/
ccflags-y += -Itechpack/camera_legacy/drivers/cam_smmu/

obj-$(CONFIG_LEGACY_CAMERA) += cam_tasklet_util.o cam_isp_packet_parser.o
obj-$(CONFIG_LEGACY_CAMERA) += irq_controller/
